version: '3'

services:
  nextjs:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "pnpm install && pnpm dev"
    env_file:
      - .env


volumes:
  data:
  node_modules:
