blank_issues_enabled: false
contact_links:
  - name: Security Contact
    about: Please report security vulnerabilities to security@learnhouse.app
  - name: Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/learnhouse/learnhouse/discussions/categories/questions
  - name: Feature Request
    about: To suggest an idea or ask about a feature, please start with a question saying what you would like to achieve. There might be a way to do it already.
    url: https://github.com/learnhouse/learnhouse/discussions/categories/questions
  - name: Show and tell
    about: Show what you built with LearnHouse or to be used with LearnHouse.
    url: https://github.com/learnhouse/learnhouse/discussions/categories/show-and-tell
