import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./font";
import { Providers } from "@/components/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-sans antialiased`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
