#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo '🏗️👷 Styling, testing and building your project before committing'

# Lint
npm run lint ||
(
        echo '⚙️❌ Lint failed  ❌⚙️'
        false;
)

# Check format
npx lint-staged && git add -A ||
(
        echo '❌❌ ERROR ❌❌ - 🤢🤮 Your styling looks disgusting. 🤢🤮
                Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Everything passes, now we can commit
echo '✅✅✅ You are lucky, you win this time... I am committing this now. ✅✅✅'